version: "3.8"
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"  
      - "6832:6832/udp"   
      - "5778:5778"     
      - "16686:16686"     
      - "4317:4317"       
      - "4318:4318"       
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - evict-network

networks:
  evict-network:
    name: evict-network 